[target.aarch64-linux-android]
ar = "C:/Users/S/AppData/Local/Android/Sdk/ndk/30.0.14904198/toolchains/llvm/prebuilt/windows-x86_64/bin/llvm-ar"
linker = "C:/Users/S/AppData/Local/Android/Sdk/ndk/30.0.14904198/toolchains/llvm/prebuilt/windows-x86_64/bin/aarch64-linux-android28-clang.cmd"

[target.armv7-linux-androideabi]
ar = "C:/Users/S/AppData/Local/Android/Sdk/ndk/30.0.14904198/toolchains/llvm/prebuilt/windows-x86_64/bin/llvm-ar"
linker = "C:/Users/S/AppData/Local/Android/Sdk/ndk/30.0.14904198/toolchains/llvm/prebuilt/windows-x86_64/bin/armv7a-linux-androideabi28-clang.cmd"

[env]
CC_aarch64_linux_android = "C:/Users/S/AppData/Local/Android/Sdk/ndk/30.0.14904198/toolchains/llvm/prebuilt/windows-x86_64/bin/aarch64-linux-android28-clang.cmd"
CXX_aarch64_linux_android = "C:/Users/S/AppData/Local/Android/Sdk/ndk/30.0.14904198/toolchains/llvm/prebuilt/windows-x86_64/bin/aarch64-linux-android28-clang++.cmd"
AR_aarch64_linux_android = "C:/Users/S/AppData/Local/Android/Sdk/ndk/30.0.14904198/toolchains/llvm/prebuilt/windows-x86_64/bin/llvm-ar"

CC_armv7-linux-androideabi = "C:/Users/S/AppData/Local/Android/Sdk/ndk/30.0.14904198/toolchains/llvm/prebuilt/windows-x86_64/bin/armv7a-linux-androideabi28-clang.cmd"
CXX_armv7-linux-androideabi = "C:/Users/S/AppData/Local/Android/Sdk/ndk/30.0.14904198/toolchains/llvm/prebuilt/windows-x86_64/bin/armv7a-linux-androideabi28-clang++.cmd"
AR_armv7-linux-androideabi = "C:/Users/S/AppData/Local/Android/Sdk/ndk/30.0.14904198/toolchains/llvm/prebuilt/windows-x86_64/bin/llvm-ar"
